from typing import Any, Dict, List, Optional

class SpecialistRegistry:
    def __init__(self) -> None: ...
    def get_specialist(self, name: str) -> Any: ...
    def list_specialists(self) -> List[str]: ...
    def register_specialist(self, name: str, specialist: Any) -> None: ...
    def load_specialist(self, name: str, config: Any = None, version: Optional[str] = None) -> Any: ...
