"""
Markdown Report Generator
=======================

Generates Markdown reports for collaborative review.
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

class MarkdownReportGenerator:
    """Generates detailed Markdown reports"""
    
    def __init__(self, reports_path: Path):
        """Initialize the Markdown report generator
        
        Args:
            reports_path: Directory where reports will be saved
        """
        self.reports_path = reports_path
        self.reports_path.mkdir(exist_ok=True)
    
    def generate_report(self, report_data: List[Dict[str, Any]]) -> Path:
        """Generate a Markdown report from the provided data
        
        Args:
            report_data: List of job report entries
            
        Returns:
            Path to the generated Markdown file
        """
        if not report_data:
            raise ValueError("No data provided for report generation")
            
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        md_path = self.reports_path / f"daily_report_{timestamp}.md"
        
        print(f"Creating Markdown report: {md_path}")
        
        content = self._generate_header(len(report_data))
        content += self._generate_job_sections(report_data)
        content += self._generate_metadata(timestamp)
        
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"Markdown report created: {md_path}")
        return md_path
    
    def _generate_header(self, job_count: int) -> str:
        """Generate the report header section"""
        return f"""# Daily Job Analysis Report - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Report Summary
- **Total Jobs Processed**: {job_count}
- **Analysis Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Report Format**: Sandy's Golden Rules 27-Column Compliant
- **Generated By**: Modular Daily Report Generator

## Jobs Analysis

"""
    
    def _generate_job_sections(self, report_data: List[Dict[str, Any]]) -> str:
        """Generate the job analysis sections"""
        content = ""
        for i, job in enumerate(report_data, 1):
            content += self._format_job_section(i, job)
        return content
    
    def _format_job_section(self, index: int, job: Dict[str, Any]) -> str:
        """Format a single job section"""
        return f"""### Job #{index}: {job['job_id']} - {job['position_title']}

**Core Job Information:**
- **Job ID**: {job['job_id']}
- **Position Title**: {job['position_title']}
- **Location**: {job['location']}
- **Location Validation**: {job['location_validation_details']}
- **Job Domain**: {job['job_domain']}
- **Match Level**: {job['match_level']}
- **Evaluation Date**: {job['evaluation_date']}

**📋 Full Content (Raw Job Description):**
```
{job['full_content']}
```

**🤖 Concise Job Description (LLM-Extracted):**
```
{job['concise_description']}
```

**🔍 Analysis Results:**
- **Has Domain Gap**: {job['has_domain_gap']}
- **Domain Assessment**: {job['domain_assessment']}
- **No-go Rationale**: {job['no_go_rationale']}
- **Application Narrative**: {job['application_narrative']}

**📋 Processing Logs:**
- **Export Job Matches Log**: {job['export_job_matches_log']}
- **Generate Cover Letters Log**: {job['generate_cover_letters_log']}
- **Reviewer Feedback**: {job['reviewer_feedback']}
- **Mailman Log**: {job['mailman_log']}
- **Process Feedback Log**: {job['process_feedback_log']}
- **Reviewer Support Log**: {job['reviewer_support_log']}
- **Workflow Status**: {job['workflow_status']}

**🧠 Sandy's Analysis:**
- **Evaluation**: {job['technical_evaluation']}
- **Story Interpretation**: {job['human_story_interpretation']}
- **Opportunity Assessment**: {job['opportunity_bridge_assessment']}
- **Growth Illumination**: {job['growth_path_illumination']}
- **Synthesis**: {job['encouragement_synthesis']}
- **Confidence Score**: {job['confidence_score']}
- **Joy Level**: {job['joy_level']}

---

"""
    
    def _generate_metadata(self, timestamp: str) -> str:
        """Generate the report metadata section"""
        return f"""## Report Metadata

**Golden Rules Compliance:**
- 27-column format structure maintained
- Full job description included (not truncated)  
- Concise job description from LLM extraction included
- Location validation details with conflict analysis included
- All analysis columns populated
- Reports saved in `/reports` directory

**Modular Architecture:**
- Content Extraction Specialist v3.4
- Location Validation Specialist (Fixed)
- Text Summarization Specialist
- Clean separation of concerns
- Testable components

**Report Generation Details:**
- **Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Excel Report**: `daily_report_{timestamp}.xlsx`
- **Markdown Report**: `daily_report_{timestamp}.md`
- **Reports Directory**: `/home/xai/Documents/sandy/reports/`

---
*Report generated using Sandy's modular architecture following Golden Rules for precision-first collaborative intelligence workflow.*
"""
