from typing import Any, Dict, Optional

class OllamaClient:
    def __init__(self, **kwargs: Any) -> None: ...
    def generate(self, prompt: str, **kwargs: Any) -> Dict[str, Any]: ...
    def chat(self, messages: list, **kwargs: Any) -> Dict[str, Any]: ...
