from typing import Any

class SpecialistRegistry:
    def __init__(self) -> None: ...
    def get_specialist(self, name: str) -> Any: ...
    def register_specialist(self, name: str, specialist: Any) -> None: ...
